/* Course-only animated illustrations. Public-record copy and progression remain in the course page. */
(()=>{
 const esc=escapeAttr;
 let portraitId=0;
 function portrait(person=0){
  const id='maya'+(++portraitId),skin=['#b67b59','#e1b18a','#875c45'][person%3],light=['#e5b28b','#f6d5b5','#be8964'][person%3],coat=['#335c75','#586384','#4d7063'][person%3];
  return `<svg class="maya-portrait" viewBox="0 0 200 225" aria-hidden="true"><defs><linearGradient id="${id}s" x2=".9" y2="1"><stop stop-color="${light}"/><stop offset="1" stop-color="${skin}"/></linearGradient><linearGradient id="${id}c" x2="1" y2="1"><stop stop-color="${coat}"/><stop offset="1" stop-color="#183043"/></linearGradient><radialGradient id="${id}h"><stop stop-color="#544039"/><stop offset="1" stop-color="#211e25"/></radialGradient></defs><ellipse cx="101" cy="215" rx="76" ry="7" fill="#061523" opacity=".3"/><g class="maya-body"><path d="M43 209L46 168Q49 138 83 130L119 130Q153 137 157 166L165 215H36Z" fill="url(#${id}c)"/><path d="M80 135L101 189L123 135Q102 146 80 135" fill="#ebe4d6"/><path d="M79 129L69 141L82 165L75 176L101 207L89 148Z" fill="#416b84"/><path d="M124 129L134 143L119 165L128 177L101 207L114 148Z" fill="#294f69"/><path d="M101 190v27" stroke="#102c3d" stroke-width="2"/><circle cx="108" cy="202" r="2" fill="#b49a6b"/><path d="M63 157L53 211" stroke="#74919c" opacity=".25" stroke-width="2"/><path d="M85 119v20q15 16 30 0v-22" fill="url(#${id}s)"/><path d="M84 127q16 15 32 0v7q-18 15-32 0" fill="#713d31" opacity=".2"/>
 <g class="maya-head"><path d="M56 122Q41 62 59 38Q75 12 110 20Q154 24 153 70L150 142Q131 149 121 130L73 137Z" fill="url(#${id}h)"/><ellipse cx="65" cy="89" rx="8" ry="14" fill="${skin}"/><ellipse cx="138" cy="89" rx="8" ry="14" fill="${skin}"/><path d="M65 61Q97 39 137 60L136 98Q132 128 101 137Q71 132 65 101Z" fill="url(#${id}s)"/><path d="M64 75Q73 62 80 45Q108 71 139 65Q151 37 121 28Q87 10 63 37Q50 54 56 91Z" fill="url(#${id}h)"/><path d="M65 56Q75 32 96 32M73 52Q82 36 100 36M105 37q19 19 32 16" stroke="#82634e" opacity=".4" fill="none" stroke-width="2"/><path d="M73 76q10-6 20-1m16 0q10-6 19 1" stroke="#493129" fill="none" stroke-width="3" stroke-linecap="round"/><g class="maya-eyes"><path d="M73 86q10-8 20 0q-10 8-20 0M109 86q10-8 20 0q-10 8-20 0" fill="#f7eee3"/><ellipse cx="84" cy="86" rx="4" ry="5" fill="#4b3b32"/><ellipse cx="119" cy="86" rx="4" ry="5" fill="#4b3b32"/><circle cx="85" cy="84" r="1.4" fill="#fff"/><circle cx="120" cy="84" r="1.4" fill="#fff"/><path d="M73 85q10-7 20 0m16 0q10-7 20 0" stroke="#4b332d" fill="none" stroke-width="1.5"/></g><path d="M101 86l-3 17q4 3 8 0" fill="none" stroke="#996046" stroke-width="1.8" stroke-linecap="round"/><ellipse cx="79" cy="102" rx="9" ry="4" fill="#ba7160" opacity=".22"/><ellipse cx="123" cy="102" rx="9" ry="4" fill="#ba7160" opacity=".22"/><g class="maya-mouth"><path d="M89 114q13 7 26-1q-9 15-26 1" fill="#80483f"/><path d="M92 114q10 5 20 0" stroke="#f6e3cd" stroke-width="3" fill="none"/></g><circle cx="64" cy="104" r="3" fill="#d2b06e"/><circle cx="138" cy="104" r="3" fill="#d2b06e"/><path d="M57 99q-2 30 13 42M145 96q2 30-13 43" stroke="#382a2b" fill="none" stroke-width="10" stroke-linecap="round"/></g>
 <g class="maya-hand"><path d="M143 168Q157 189 177 165" fill="none" stroke="${coat}" stroke-width="23" stroke-linecap="round"/><path d="M174 164l-4-14q-1-6 3-5l6 12-2-25q0-5 4-3l3 25 2-29q1-4 4-1l-1 30 5-24q2-4 4 0l-4 28q-2 16-14 16Z" fill="url(#${id}s)"/><path d="M177 159q7-1 13 4" stroke="#986247" fill="none" stroke-width="1.3"/></g><path d="M55 185q9 9 24 10l27-4q7 3 0 8l-25 7q-18 1-30-8" fill="url(#${id}s)"/></g></svg>`;
 }
 const controls=label=>`<div class="visual-controls"><span class="visual-label">${label}</span><div class="control-group"><button class="replay-visual" data-replay-visual>Reset</button><button class="visual-step-btn" data-visual-next>Start walkthrough →</button></div></div>`;
 const shell=(label,title,inside)=>`<div class="visual immersive-visual"><div class="visual-story"><header><div class="visual-label">${label}</div><div class="visual-story-title">${title}</div></header>${inside}</div></div>`;
 const room=(kind,inner='',extra='')=>`<div class="lesson-environment environment-${kind} ${extra}" aria-hidden="true"><div class="environment-light"></div>${inner}<div class="environment-vignette"></div></div>`;
 const sheet=()=>'<div class="scene-paper"><span>PROPOSED BILL</span><i></i><i></i><i></i><i></i><b>For review</b></div>';
 conceptVisual=function(s){
  const d=currentDeep(),parts=conceptParts(s);let labels=parts.length>1?parts:['Understand','Verify','Practice'];let notes=labels.map((x,i)=>[d.meaning,d.why,d.example][i%3]);
  if(activeLevel===0&&activeSlide===0){labels=['Legislature','Executive','Courts'];notes=['The General Assembly debates and passes laws.','Executive officials and agencies carry out the law.','Courts interpret the law and resolve disputes.']}
  const kind=activeLevel===1||activeLevel===0&&activeSlide===2?'draft':activeLevel===4||activeLevel===0&&activeSlide===3?'records':'hearing';
  return shell('Explore the institution',esc(s.caption||'From an idea to public action'),room(kind,sheet(), 'concept-environment')+`<div class="scene-stations">${labels.map((x,i)=>`<button class="scene-station" data-scene-pick="${i}" data-seq data-note="${esc(notes[i])}"><span>0${i+1}</span><b>${esc(x)}</b></button>`).join('')}</div><div class="visual-story-status" aria-live="polite"></div>`+controls('Follow the roles'));
 };
 peopleVisual=function(s){return shell('Inside the hearing room','Different roles. One public record.',room('hearing',`<div class="room-speakers">${s.people.map((p,i)=>p[1]==='Bill'?`<div class="speaker-prop">${sheet()}</div>`:`<div class="room-speaker" data-person="${i}">${portrait(i)}</div>`).join('')}</div><div class="witness-desk"><i></i><i></i><i></i></div>`)+`<div class="scene-stations">${s.people.map((p,i)=>`<button class="scene-station" data-scene-pick="${i}" data-seq data-note="${esc(p[1]+' — '+p[2])}"><b>${esc(p[1])}</b><small>${esc(p[2])}</small></button>`).join('')}</div><div class="visual-story-status" aria-live="polite"></div>`+controls('Choose a speaker'))};
 workflowVisual=function(s){let kind=activeLevel===3?'draft':activeLevel===4?'records':'hearing';return shell('Follow the work','Each step changes what happens next',room(kind,`<div class="traveling-file">${sheet()}</div><div class="desk-nameplate">${esc(s.steps[0])}</div>`,'workflow-environment')+`<div class="scene-stations workflow-stations">${s.steps.map((x,i)=>`<button class="scene-station" data-scene-pick="${i}" data-seq data-note="${esc(x+(i<s.steps.length-1?' → '+s.steps[i+1]:'. End of this sequence.'))}"><span>${i+1}</span><b>${esc(x)}</b></button>`).join('')}</div><div class="visual-story-status" aria-live="polite"></div>`+controls('Trace the sequence'))};
 // Keep the real record, quiz and redline interactions; add material detail to their workspaces.
 const baseMake=makeVisual;
 makeVisual=function(s){let html=baseMake(s);if(s.type==='real')html=html.replace('class="record-sim"','class="record-sim tactile-record"');if(s.type==='compare')html=html.replace('class="redline-stage"','class="redline-stage tactile-drafting"');return html};
 function react(){
  const active=slide.querySelector('[data-seq].active');
  slide.querySelectorAll('.room-speaker').forEach((el,i)=>{el.classList.toggle('is-speaking',i===visualStep);el.classList.toggle('is-listening',visualStep>=0&&i!==visualStep)});
  const scene=slide.querySelector('.lesson-environment');if(scene){scene.classList.remove('scene-action');void scene.offsetWidth;scene.classList.add('scene-action');scene.style.setProperty('--file-position',Math.max(0,visualStep)*12+'%');scene.dataset.step=visualStep;const plate=scene.querySelector('.desk-nameplate');if(plate&&active)plate.textContent=active.querySelector('b').textContent}
  document.querySelectorAll('.guide .maya-portrait,.coach-pop .maya-portrait').forEach(el=>{el.classList.remove('explaining');void el.getBoundingClientRect();el.classList.add('explaining')});
 }
 const oldAdvance=advanceVisual;advanceVisual=function(){oldAdvance();react()};
 const oldReset=resetVisual;resetVisual=function(){oldReset();react();slide.querySelectorAll('.scene-action').forEach(el=>el.classList.remove('scene-action'))};
 const oldRender=renderSlide;renderSlide=function(){oldRender();slide.querySelectorAll('[data-scene-pick]').forEach(el=>el.onclick=()=>{visualStep=Number(el.dataset.scenePick)-1;advanceVisual()});slide.classList.remove('scene-enter');void slide.offsetWidth;slide.classList.add('scene-enter')};
 document.querySelectorAll('.avatar,.intro-avatar,.coach-character').forEach(el=>el.innerHTML=portrait());
 const avatar=document.querySelector('.guide .avatar');const guideButton=document.createElement('button');guideButton.className='maya-guide-button';guideButton.innerHTML=avatar.innerHTML;guideButton.setAttribute('aria-label','Open Maya’s learning guide');guideButton.setAttribute('aria-expanded','false');avatar.replaceWith(guideButton);
 document.querySelector('.guide-name').textContent='Maya · select me for a tip';
 showCoach=function(){clearTimeout(coachTimer);const s=course[activeLevel].slides[activeSlide];coachPopText.textContent=s.guide;coachAnimate.style.display=['quiz','games'].includes(s.type)?'none':'inline-flex';coachPop.inert=false;coachPop.classList.add('show');guideButton.setAttribute('aria-expanded','true');coachPop.querySelector('.maya-portrait').classList.add('explaining');coachDismiss.focus({preventScroll:true})};
 const oldHide=hideCoach;hideCoach=function(){const wasOpen=coachPop.classList.contains('show');oldHide();coachPop.inert=true;guideButton.setAttribute('aria-expanded','false');if(wasOpen&&coachPop.contains(document.activeElement))guideButton.focus({preventScroll:true})};
 coachPop.inert=true;
 guideButton.onclick=()=>coachPop.classList.contains('show')?hideCoach():showCoach();coachDismiss.onclick=hideCoach;
 coachAnimate.onclick=()=>{advanceVisual();coachPopText.textContent=slide.querySelector('.visual-story-status')?.textContent||course[activeLevel].slides[activeSlide].guide};
 const motion=document.createElement('button');motion.className='course-motion';motion.type='button';motion.setAttribute('aria-label','Pause course animations');document.querySelector('.lessonbar').append(motion);
 let paused=localStorage.getItem('ohCourseMotionPausedV1')==='true';const reduced=matchMedia('(prefers-reduced-motion: reduce)');function setMotion(){document.documentElement.classList.toggle('course-motion-paused',paused||reduced.matches);motion.textContent=paused?'Play motion':'Pause motion';motion.setAttribute('aria-pressed',String(paused));motion.disabled=reduced.matches;motion.title=reduced.matches?'Motion is reduced by your device preference':'Control character and scene animation';motion.setAttribute('aria-label',paused?'Play course animations':'Pause course animations')};motion.onclick=()=>{paused=!paused;localStorage.setItem('ohCourseMotionPausedV1',String(paused));setMotion()};reduced.addEventListener('change',setMotion);setMotion();
})();
